### ISSUE TITLE
Improve the "Learn More" buttons in the popup box

### ISSUE THREAD

**Issue by rraub** [gios-asu/sustainable-cities-city-map#10]
* Remove the html in the url field for each feature in the geojson.
* Improve the layout of the popups so that the user can see all of the content without having to move the map around. 
* I think it's unnecessary to say which feature (solar, GI, etc…) it is within the pop-up windows themselves; clicking on the icons already makes it clear that something is solar or green infrastructure, etc. Getting rid of these titles will help to save room within the pop-up windows

**Comment by chasethenag420** [comment]
Regarding last bullet point keeping feature name may help in case multiple features are present at same location. Currently I implemented in a way that multiple feature details are shown in pop up with along its feature name.

**Comment by rraub** [comment]
ok, that makes sense if there are multiple features in one popup.
