### ISSUE TITLE
Icons can be improved

### ISSUE THREAD

**Issue by rraub** [gios-asu/sustainable-cities-city-map#8]
* The icons should have a hover over effect so there's an indication that they hold information. currently, the only way to know is by clicking on them, but there are no indicators that they should/can be clicked on
* The icons on the overall map aren't interactive, but I think it would be easier to navigate if they are interactive.
* Icon congestion (ex. Bike share) – is there a way to clean up the number of icons based on the depth of the map?  Bike share sites in Phoenix is very congested – is it easier to have one bike in a wide view and then more will appear as one scrolls down into the map?
* Icon look – is there a better, cleaner icon to use to depict this item?

**Comment by rraub** [comment]
Still have to add a hover over effect for the icons (or remove the hover over for the city boundaries).
Improve the visibility of the icons so they contrast more - either lighten the city shades or in the case of the building, find another icon that is of one building and more distinguishable when its small.
![screen shot 2016-04-15 at 2 30 36 pm](https://cloud.githubusercontent.com/assets/295804/14575438/a47a583c-0316-11e6-845f-c1c92b3092bf.png)

**Comment by chasethenag420** [comment]
On hover doesn't seem to be good option in case when there are multiple features present at same location and pop up contains description about each feature we may see a scroll bar but we can't really scroll to see all the features present in pop up window when we move mouse it we out of feature so pop up disappears.

**Comment by chasethenag420** [comment]
@rraub  any suggestion on how to handle this?

**Comment by rraub** [comment]
fixed in https://github.com/gios-asu/sustainable-cities-city-map/pull/16/commits/24bafbff94d8378daf1874e542ce85ee0155b57d
